version: "3.3"  # optional since v1.27.0
services:
  web:
    build: 
      context: .
    image: go-app-ms:latest
    ports:
      - "8080:8080"
    restart: always
    networks:
      - web

  
networks:
  web: